### ISSUE TITLE
Upgrade the Material.Blazor project to ASP.NET5

### ISSUE THREAD

**Issue by simonziegler** [Material-Blazor/Material.Blazor#261]
- Do this only after full release (i.e. not release candidates).
- This is a **breaking change** so do this with v2.0.0.
- Keep v1 of Material.Blazor compatible with ASP.NET 3.1 LTS.

**Comment by MarkStega** [comment]
Consider multi-targeting with support for .NET Standard 2.1 as well as .NET 5 (See [https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/)). We then drop .Net Standard 2.1 support only when it is desirable to use a .NET 5 only construct.

**Comment by MarkStega** [comment]
We don't even have to drop .Net Standard 2.1 support if we use a .Net 5 only construct but we do have to guard that code to prevent a runtime failure on .Net 3.x

**Comment by MarkStega** [comment]
The multi-targeting worked fine however DocFx will not run in a pure .Net 5 environment

**Comment by simonziegler** [comment]
We've agreed to drop dual support:

- remove all references to netstandard2.1
- check that DocFX builds successfully
- don't do this until after 16 Nov 2020 because net5.0 will then become part of standard github actions

**Comment by MarkStega** [comment]
It turns out that with the proper github actions environment we do not need to drop the support of NS2.1; Everything builds properly now that the environment simply adds the DN5 sdk & runtimes to the mix.

Since Blazor is supported in the DN 3.1 release which is LTS until December 3, 2022 there is some merit to keeping the NS2.1 support.

So I propose revisiting the plus/minus ledger of keeping NS2.1 support.
