### ISSUE TITLE
Unbundled JS is actually bundled

### ISSUE THREAD

**Issue by simonziegler** [Material-Blazor/Material.Blazor#314]
`unbundled.js` presently has all material modules due to the new TS mechanism needing to bundle this stuff. Investigate if it's possible to create a new genuinely unbundled JS package. If not, remove unbundled and consider changing JS package name. This is a breaking change, so only for v2.0.0.

Also explore why given this, `bundled.min.js` is 4x larger than the `unbundled min.js1. The few unimplemented components would not be large enough to account for this. Are we double including anything?

**Comment by simonziegler** [comment]
While we're at it, also review CSS bundling and naming.

**Comment by MarkStega** [comment]
After thinking about this for a few hours, I believe that we should consider delivering just one file each of css & js. To wit:

Material.Blazor.min.css - All of the css needed from Material, MaterialIcons, and Material.Blazor
Material.Blazor.min.js - All of the js needed from Material & Material.Blazor

We can have the non-minified versions built into a working directory in the repository (probably git ignored so they don't even end up in our git repository). So they are available for debug we have the build copy them into wwwroot after the build of the dll. We make certain they are deleted from wwwroot in the prebuild css/js generation steps. This way we don't increase the dll/NuGet package size but still have them available for that special case of wanting to debug.

**Comment by simonziegler** [comment]
For we cannot have one file, because users need the unbundled variant in order to create themes. I'm on the fence re javascript.

**Comment by MarkStega** [comment]
Why? It seems that the order matters, the theme has to come after the bundle and it will override css in the bundle.

**Comment by simonziegler** [comment]
That feels dangerous to me and also involves doubling the download. I think we should keep what we know works and seems like the accepted pattern.

**Comment by MarkStega** [comment]
After reflection I believe that we should still consider delivering just one file each of css & js with the content modified from the comment above:

MaterialBlazor.min.css - All of the css needed from Material.Blazor (no bundle of Material css but including all 3 icon fonts needed for M.B)
MaterialBlazor.min.js - All of the js needed from Material & Material.Blazor (Essentially this is a bundle of the required Material & Material.Blazor js since that is what gets produced by WebPack). Using this guarantees that we have the appropriate js from both sources.

>>>Also explore why given this, bundled.min.js is 4x larger than the `unbundled min.js1. The few unimplemented components would not be large enough to account for this. Are we double including anything?

Looking at unbundled.js (1.1Mb), material-components-web.js (1.1Mb) and then bundled.js (2.4Mb) explains the difference since (in essence) bundled was two copies of Material JS once unbundled included most of Material JS. There was some more added (200Kb) which I suppose came from the Beautify process. In any case, there is no practical way (that I know) to create a truly unbundled js
