### ISSUE TITLE
Suggestion: Components for LayoutGrid

### ISSUE THREAD

**Issue by marinasundstrom** [Material-Blazor/Material.Blazor#359]
I'm new to Material design (and Material components), and I have realized that the CSS for grids is a bit complex with all the long class names.

Maybe it would be a great idea to create components that simplify it.

This is my concept:

```razor
<LayoutGrid Span="6" SpanDesktop="6" SpanTablet="4" SpanPhone="2">
    <Inner>
        <Cell Order="2"> </Cell>
        <Cell Order="1"> </Cell>
    </Inner>
</LayoutGrid>
```

**Comment by simonziegler** [comment]
@robertsundstrom thanks for the suggestion, but we won't be doing this. The reason is that a core design principle of Material.Blazor is that we never deal with layout. MB assumes that the consumer is familiar with Material Components Web and that they will control the layout and its CSS themselves. This is what we do in our apps.

Simon
